/**
 * @file Service Worker registration helper
 * @purpose Registers the push-capable service worker (/sw.js) and
 *          exports utilities for checking registration state.
 *
 * The actual service worker source lives at client/static/sw.js
 * (or generated by the build tool). This module handles registration
 * lifecycle so other modules do not import navigator.serviceWorker directly.
 *
 * @depends navigator.serviceWorker (Browser Service Worker API)
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SwRegistrationResult {
  ok: boolean;
  registration?: ServiceWorkerRegistration;
  error?: string;
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

/**
 * Register the application service worker.
 *
 * Idempotent — returns the existing registration if already registered.
 * Call once during app boot (e.g., in +layout.svelte onMount).
 *
 * @returns Object with `ok` flag and the registration or error message.
 */
export async function registerServiceWorker(): Promise<SwRegistrationResult> {
  if (!("serviceWorker" in navigator)) {
    return { ok: false, error: "Service workers not supported" };
  }

  try {
    const registration = await navigator.serviceWorker.register("/sw.js", {
      scope: "/",
    });
    console.info("[sw] Service worker registered", registration.scope);
    return { ok: true, registration };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[sw] Service worker registration failed", message);
    return { ok: false, error: message };
  }
}

/**
 * Check whether the service worker is currently active.
 *
 * @returns true if an active controller exists for this page.
 */
export function isServiceWorkerActive(): boolean {
  return (
    "serviceWorker" in navigator && navigator.serviceWorker.controller !== null
  );
}
